apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-b
  template:
    metadata:
      labels:
        app: server-b
    spec:
      containers:
        - name: server-b
          image:  docker.io/yuhaibao/aws-server-b:1.0.20
          env:
            - name: AUTHOR
              value: server-b
          ports:
            - containerPort: 7033
---
apiVersion: v1
kind: Service
metadata:
  name: server-b
spec:
  ports:
    - port: 7033
      protocol: TCP
      targetPort: 7033
  type: ClusterIP
  selector:
    app: server-b